apiVersion: v1
kind: PersistentVolume

metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
